CREATE TABLE lmsdb.activitylog (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ActivityType TINYINT(4) NOT NULL,
  ActivityTime DATETIME NOT NULL,
  UserID VARCHAR(100) NOT NULL DEFAULT '',
  UserName VARCHAR(255) NOT NULL DEFAULT '',
  Origin VARCHAR(255) NOT NULL DEFAULT '',
  Description VARCHAR(255) DEFAULT NULL,
  IsRead TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;