CREATE TABLE lmsdb.appsetting (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  AppKey VARCHAR(255) NOT NULL DEFAULT '',
  AppVal VARCHAR(5000) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;