CREATE TABLE lmsdb.appuser (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) DEFAULT NULL,
  UserType VARCHAR(10) NOT NULL DEFAULT '',
  UserID VARCHAR(100) NOT NULL DEFAULT '',
  Email VARCHAR(50) DEFAULT NULL,
  Mobile VARCHAR(255) DEFAULT NULL,
  Password VARCHAR(100) NOT NULL DEFAULT '',
  UserPerm VARCHAR(2000) DEFAULT NULL,
  IsPassReset BIT(1) NOT NULL DEFAULT b'0',
  ResetPassValidity DATE DEFAULT NULL,
  ResetPassContext VARCHAR(255) DEFAULT NULL,
  IsActive BIT(1) NOT NULL DEFAULT b'0',
  DOB DATE DEFAULT NULL,
  CustomData VARCHAR(4000) DEFAULT NULL,
  Gender VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;