CREATE TABLE lmsdb.mjob (
  JobId BIGINT(20) NOT NULL AUTO_INCREMENT,
  RefNo VARCHAR(50) NOT NULL DEFAULT '',
  Command VARCHAR(25) NOT NULL DEFAULT '',
  CommandData VARCHAR(5000) DEFAULT NULL,
  Priority VARCHAR(2) NOT NULL DEFAULT '',
  CreatedOn DATETIME DEFAULT NULL,
  CreatedBy BIGINT(20) DEFAULT NULL,
  FinishedOn DATETIME DEFAULT NULL,
  ErrorCode VARCHAR(10) DEFAULT NULL,
  ErrorMsg VARCHAR(255) DEFAULT NULL,
  Status TINYINT(4) DEFAULT NULL,
  ValidFrom DATETIME DEFAULT NULL,
  ValidTo DATETIME DEFAULT NULL,
  PRIMARY KEY (JobId)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;