CREATE TABLE lmsdb.tblmstudent (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL DEFAULT '',
  RegNo VARCHAR(25) NOT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  ContactNo VARCHAR(50) NOT NULL DEFAULT '',
  Email VARCHAR(50) NOT NULL DEFAULT '',
  StandardID INT(11) NOT NULL,
  CreatedOn DATE NOT NULL,
  CreatedBy INT(11) DEFAULT NULL,
  LoginUserId BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;


CREATE TABLE lmsdb.tblrstudentclassroom (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  StudentID INT(11) NOT NULL,
  ClassRoomID INT(11) NOT NULL,
  CreatedOn DATE NOT NULL,
  ClosedOn DATE DEFAULT NULL,
  CreatedBy VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;