CREATE TABLE lmsdb.tblmteacher (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL DEFAULT '',
  Address VARCHAR(500) DEFAULT NULL,
  ContactNo VARCHAR(50) NOT NULL DEFAULT '',
  Email VARCHAR(50) NOT NULL DEFAULT '',
  EducationalQualification VARCHAR(500) DEFAULT NULL,
  CreatedOn DATE DEFAULT NULL,
  CreatdBy INT(11) DEFAULT NULL,
  LoginUserId BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;